# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
executors:
  container:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: mysql:8.0.24
      - image: redis:6.2.2
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
  virtual_machine:
    machine:
      image: ubuntu-2004:202008-01
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  build:
    executor:
      name: virtual_machine
    steps:
      - checkout

      - run: docker-compose -f devtool/docker/docker-compose.yaml up -d
      - run: sleep 10

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle build

      - run: gradle jacocoTestReport

      - store_test_results:
          path: build/test-results/test

      - store_artifacts:
          path: build/reports/test
          destination: junit
      - store_artifacts:
          path: build/reports/checkstyle
          destination: checkstyle
      - store_artifacts:
          path: build/reports/spotbugs
          destination: spotbugs
      - store_artifacts:
          path: build/reports/project/dependencies
          destination: project-dependencies
      - store_artifacts:
          path: build/reports/jacoco/test/html
          destination: jacoco